CREATE TABLE owners(
    id IDENTITY NOT NULL PRIMARY KEY,
    type_owner CHAR(1) NOT NULL,
    CHECK (type_owner IN ('F', 'U'))
);

CREATE TABLE persons(
    id_person INT PRIMARY KEY,
    firstName VARCHAR(70) NOT NULL,
    lastName VARCHAR(70) NOT NULL,
    birthday DATE NOT NULL,
    FOREIGN KEY (id_person) REFERENCES owners (id) ON UPDATE CASCADE
);

CREATE TABLE contractors(
    id_contractor INT PRIMARY KEY,
    name VARCHAR(70) NOT NULL,
    inn VARCHAR(10) NOT NULL UNIQUE,
    FOREIGN KEY (id_contractor) REFERENCES owners (id) ON UPDATE CASCADE
);

CREATE TABLE accounts(
    id IDENTITY NOT NULL PRIMARY KEY,
    number VARCHAR(20) NOT NULL UNIQUE,
    id_owner INT,
    balance DECIMAL DEFAULT 0,
    status_account VARCHAR(5) DEFAULT 'OPEN',
    CHECK (status_account IN ('OPEN', 'CLOSE')),
    FOREIGN KEY (id_owner) REFERENCES owners (id) ON UPDATE CASCADE
);

CREATE TABLE cards(
    id IDENTITY NOT NULL PRIMARY KEY,
    number VARCHAR(16) NOT NULL UNIQUE,
    id_account INT,
    status_card VARCHAR(5) DEFAULT 'OPEN',
    CHECK (status_card IN ('OPEN', 'CLOSE')),
    FOREIGN KEY (id_account) REFERENCES accounts (id) ON UPDATE CASCADE
);

CREATE TABLE accountTransactions(
    id IDENTITY NOT NULL PRIMARY KEY,
    id_from INT NOT NULL,
    id_to INT NOT NULL,
    amount DECIMAL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    status_transaction CHAR(1) DEFAULT NULL,
    message VARCHAR(255) DEFAULT NULL,
    CHECK (status_transaction IN ('Y', 'N', NULL)),
    FOREIGN KEY (id_from) REFERENCES accounts(id) ON UPDATE CASCADE,
    FOREIGN KEY (id_to) REFERENCES accounts(id) ON UPDATE CASCADE
);

INSERT INTO OWNERS (TYPE_OWNER) VALUES ('F');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('F');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('F');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('F');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('F');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('U');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('U');
INSERT INTO OWNERS (TYPE_OWNER) VALUES ('U');

INSERT INTO PERSONS (id_person, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES(1, 'Eugeny', 'Avdeev', '1995-06-23');
INSERT INTO PERSONS (id_person, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES(2, 'Stas', 'Sviridov', '1992-09-11');
INSERT INTO PERSONS (id_person, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES(3, 'Sasha', 'Zhavo', '1993-11-28');
INSERT INTO PERSONS (id_person, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES(4, 'Alina', 'Ismagilova', '1994-12-02');
INSERT INTO PERSONS (id_person, FIRSTNAME, LASTNAME, BIRTHDAY) VALUES(5, 'Vlad', 'Aparin', '1997-03-07');

INSERT INTO contractors (id_contractor, name, inn) VALUES(6, 'Granit', '1234567890');
INSERT INTO contractors (id_contractor, name, inn) VALUES(7, 'IBS', '5674209809');
INSERT INTO contractors (id_contractor, name, inn) VALUES(8, 'COFF', '1734507820');

INSERT INTO ACCOUNTS (NUMBER, ID_OWNER, BALANCE) VALUES ('12345672901234567890', 1, 1000);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('12345672901234567891', 1);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('12345678906204567892', 2);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('12345678901234567893', 3);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER, BALANCE) VALUES ('12345678901234567894', 4, 500);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('12345678901234567895', 5);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('15345678901234567896', 6);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER, BALANCE) VALUES ('12635678901234567897', 7, 200000);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER, BALANCE) VALUES ('12345678901234367898', 7, 8000);
INSERT INTO ACCOUNTS (NUMBER, ID_OWNER) VALUES ('12345678961234567899', 8);

INSERT INTO CARDS (NUMBER, ID_ACCOUNT) VALUES ('1234567812345677', 1);
INSERT INTO CARDS (NUMBER, ID_ACCOUNT) VALUES ('1234567812345678', 1);
INSERT INTO CARDS (NUMBER, ID_ACCOUNT) VALUES ('1234567812345679', 1);
INSERT INTO CARDS (NUMBER, ID_ACCOUNT) VALUES ('1234567887654321', 3);
INSERT INTO CARDS (NUMBER, ID_ACCOUNT) VALUES ('1234567891234567', 5);

INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (1, 2, 1000);
INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (1, 2, 299.9);
INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (8, 9, 10);
INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (8, 10, 500);
INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (8, 5, 100);
INSERT INTO ACCOUNTTRANSACTIONS (ID_FROM, ID_TO, AMOUNT) VALUES (5, 8, 499.50);
